#!/usr/bin/env bash
#Bash script that pings an IP address passed as an argument.
#ping using option -c count among i, t, ,s.
#Here we testting network speed refrencing google port 8.8.8.8
if [ -z "$1" ]; then
   echo "Usage: $0 {IP_ADDRESS}"
   exit 1
fi
#arfument
argument = $1
#ping for count port as arfument
ping -c 5 "$argument"
